[package]
name = "rfm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.2"
crossterm = "0.20"
tui = { version = "0.16", default-features = false, features = ['crossterm'] }
